workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic_api_key
    environment:
      node: 20
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.corelink.inventory"
        XCODE_WORKSPACE: "CoreLink.xcworkspace"
        XCODE_SCHEME: "CoreLink"
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Install Expo CLI
        script: npm install -g expo-cli eas-cli
      - name: Prebuild iOS
        script: npx expo prebuild --platform ios --clean
      - name: Install CocoaPods
        script: cd ios && pod install
      - name: Generate certificate key
        script: |
          # Generate RSA private key for certificate signing
          ssh-keygen -t rsa -b 2048 -m PEM -f /tmp/cert_key -N ""
          export CM_CERTIFICATE_PRIVATE_KEY=/tmp/cert_key
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_DEVELOPMENT \
            --create \
            --certificate-key=@file:/tmp/cert_key
      - name: Use signing profiles
        script: xcode-project use-profiles
      - name: Build iOS
        script: |
          cd ios
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/CoreLink.xcarchive \
            archive
      - name: Create IPA
        script: |
          # Create export options plist for development distribution
          cat > /tmp/ExportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>teamID</key>
              <string>2R8F9ZVV2B</string>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath ios/build/CoreLink.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist /tmp/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - ios/build/*.ipa
      - "*.ipa"
